CREATE TABLE user_profiles (
id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
first_name VARCHAR(255),
last_name VARCHAR(255),
phone_number VARCHAR(255),
street_name VARCHAR(50),
house_number VARCHAR(3),
PLZ VARCHAR(5),
city VARCHAR(30)
);

CREATE TABLE categories (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL,
category_id INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
description TEXT,
price INT NOT NULL,
stock INT DEFAULT 0
);

CREATE TABLE tags (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE wishlists (
user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
PRIMARY KEY (user_id, product_id)
);

CREATE TABLE orders (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
status VARCHAR(15) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
CHECK (status IN ('Prepared', 'In delivery', 'Delivered'))
);

CREATE TABLE order_items (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
price_per_unit DECIMAL(10,2) NOT NULL,
quantity INT DEFAULT 0
);